<?php

/**
 * @file
 * Enables Drupal to send e-mail using the PostageApp API.
 * 
 */

/**
* Implements hook_help().
*/
function postageapp_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#postageapp":
      $output = '<p>'.  t("Allows you to send mail using the PostageApp API.  See http://postageapp.com for more info.") .'</p>';
      break;
    case "admin/settings/postageapp":
      $output = '<p>'.  t("Enter text here to describe how to set up postageApp.  See http://postageapp.com for more info.") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_menu()
 */
function postageapp_menu() {
  $items['admin/config/services/postageapp'] = array(
    'title' => 'PostageApp settings',
    'description' => t('Settings for PostageApp integration'),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('postageapp_admin_form'),
    'access arguments' => array('administer postageapp'),
    'file' => 'include/postageapp.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_permission()
 */
function postageapp_permission() {
  return array(
    'administer postageapp' => array(
      'title' => t('Administer Postageapp'),
      'description' => t('Perform administration tasks for Postageapp.'),
    ),
  );
}

/*
function drupal_mail_wrapper($message) {
  $q = new PostageApp(variable_get('postageapp_api_key', '')); 
  $return = $q->mail(
    $message['to'], 
    $message['subject'],
    $message['body'],
    $message['headers']
  );
  
  if (!($return->response->status == 'ok')) {
    watchdog('mail', 'PostageApp: %message.', array('%message' => $return->response->message), WATCHDOG_ERROR);
    return 0;
  } else {
    return $return;
  }
}*/


